-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.batch (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  institutions_id uuid,
  institution_code character varying NOT NULL,
  batch_year integer NOT NULL,
  batch_name character varying NOT NULL,
  batch_code character varying NOT NULL,
  start_date date,
  end_date date,
  status boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT batch_pkey PRIMARY KEY (id),
  CONSTRAINT batch_table_institutions_id_fkey FOREIGN KEY (institutions_id) REFERENCES public.institutions(id)
);
CREATE TABLE public.course (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  institutions_id uuid,
  regulation_id bigint,
  offering_department_id uuid,
  institution_code character varying NOT NULL,
  regulation_code character varying NOT NULL,
  offering_department_code character varying,
  course_code character varying NOT NULL,
  course_name character varying NOT NULL,
  display_code character varying,
  course_category character varying CHECK (course_category::text = ANY (ARRAY['Theory'::character varying, 'Practical'::character varying, 'Project'::character varying, 'Non Academic'::character varying, 'Theory + Practical'::character varying, 'Theory + Project'::character varying, 'Field Work'::character varying, 'Community Service'::character varying, 'Group Project'::character varying]::text[])),
  course_type character varying CHECK (course_type::text = ANY (ARRAY['Core'::character varying, 'Generic Elective'::character varying, 'Skill Enhancement'::character varying, 'Ability Enhancement'::character varying, 'Language'::character varying, 'English'::character varying, 'Advance learner course'::character varying, 'Additional Credit course'::character varying, 'Discipline Specific elective'::character varying, 'Audit Course'::character varying, 'Bridge course'::character varying, 'Non Academic'::character varying, 'Naanmuthalvan'::character varying]::text[])),
  course_part_master character varying CHECK (course_part_master::text = ANY (ARRAY['Part I'::character varying, 'Part II'::character varying, 'Part III'::character varying, 'Part IV'::character varying, 'Part V'::character varying]::text[])),
  credit numeric,
  split_credit boolean DEFAULT false,
  theory_credit numeric,
  practical_credit numeric,
  qp_code character varying,
  e_code_name character varying CHECK (e_code_name::text = ANY (ARRAY['Tamil'::character varying, 'English'::character varying, 'French'::character varying, 'Malayalam'::character varying, 'Hindi'::character varying]::text[])),
  duration_hours integer,
  evaluation_type character varying CHECK (evaluation_type::text = ANY (ARRAY['CA'::character varying, 'ESE'::character varying, 'CA + ESE'::character varying]::text[])),
  result_type character varying DEFAULT 'Mark'::character varying CHECK (result_type::text = ANY (ARRAY['Mark'::character varying, 'Status'::character varying]::text[])),
  self_study_course boolean DEFAULT false,
  outside_class_course boolean DEFAULT false,
  open_book boolean DEFAULT false,
  online_course boolean DEFAULT false,
  dummy_number_not_required boolean DEFAULT true,
  annual_course boolean DEFAULT false,
  multiple_qp_set boolean DEFAULT false,
  no_of_qp_setter integer,
  no_of_scrutinizer integer,
  fee_exception boolean DEFAULT false,
  syllabus_pdf_url text,
  description text,
  status boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT course_pkey PRIMARY KEY (id),
  CONSTRAINT course_institutions_id_fkey FOREIGN KEY (institutions_id) REFERENCES public.institutions(id),
  CONSTRAINT course_regulation_id_fkey FOREIGN KEY (regulation_id) REFERENCES public.regulations(id),
  CONSTRAINT course_offering_department_id_fkey FOREIGN KEY (offering_department_id) REFERENCES public.department(id)
);
CREATE TABLE public.course_mapping (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  institutions_id uuid,
  program_id uuid,
  course_id uuid,
  batch_id uuid,
  institution_code character varying NOT NULL,
  program_code character varying NOT NULL,
  course_code character varying NOT NULL,
  batch_code character varying NOT NULL,
  course_group character varying CHECK (course_group::text = ANY (ARRAY['General'::character varying, 'Elective - I'::character varying, 'Elective - II'::character varying, 'Elective - III'::character varying, 'Elective - IV'::character varying, 'Elective - V'::character varying, 'Elective - VI'::character varying]::text[])),
  semester_code character varying,
  course_order integer,
  internal_max_mark numeric,
  internal_pass_mark numeric,
  internal_converted_mark numeric,
  external_max_mark numeric,
  external_pass_mark numeric,
  external_converted_mark numeric,
  total_pass_mark numeric,
  total_max_mark numeric,
  annual_semester boolean DEFAULT false,
  registration_based boolean DEFAULT false,
  status boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT course_mapping_pkey PRIMARY KEY (id),
  CONSTRAINT course_mapping_batch_id_fkey FOREIGN KEY (batch_id) REFERENCES public.batch(id),
  CONSTRAINT course_mapping_institutions_id_fkey FOREIGN KEY (institutions_id) REFERENCES public.institutions(id),
  CONSTRAINT course_mapping_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.program(id),
  CONSTRAINT course_mapping_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.course(id)
);
CREATE TABLE public.degree (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  institutions_id uuid,
  institution_code character varying NOT NULL,
  degree_code character varying NOT NULL,
  degree_name character varying NOT NULL,
  display_name character varying,
  description text,
  status boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT degree_pkey PRIMARY KEY (id),
  CONSTRAINT degree_institutions_id_fkey FOREIGN KEY (institutions_id) REFERENCES public.institutions(id)
);
CREATE TABLE public.department (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  institutions_id uuid,
  institution_code character varying NOT NULL,
  department_code character varying NOT NULL,
  department_name character varying NOT NULL,
  display_name character varying,
  description text,
  stream character varying CHECK (stream::text = ANY (ARRAY['Arts'::character varying, 'Science'::character varying, 'Management'::character varying, 'Commerce'::character varying, 'Engineering'::character varying, 'Medical'::character varying, 'Law'::character varying]::text[])),
  status boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT department_pkey PRIMARY KEY (id),
  CONSTRAINT department_institutions_id_fkey FOREIGN KEY (institutions_id) REFERENCES public.institutions(id)
);
CREATE TABLE public.institutions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  institution_code character varying UNIQUE,
  name character varying NOT NULL,
  phone character varying,
  email character varying,
  website character varying,
  created_by uuid,
  counselling_code character varying,
  category character varying CHECK (category::text = ANY (ARRAY['ug'::character varying::text, 'pg'::character varying::text, 'ug_pg'::character varying::text])),
  accredited_by character varying,
  address_line1 character varying,
  address_line2 character varying,
  address_line3 character varying,
  city character varying,
  state character varying,
  country character varying,
  logo_url text,
  transportation_dept jsonb,
  administration_dept jsonb,
  accounts_dept jsonb,
  admission_dept jsonb,
  placement_dept jsonb,
  anti_ragging_dept jsonb,
  institution_type character varying,
  pin_code character varying,
  timetable_type character varying DEFAULT 'week_order'::character varying CHECK (timetable_type::text = ANY (ARRAY['day_order'::character varying::text, 'week_order'::character varying::text])),
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT institutions_pkey PRIMARY KEY (id),
  CONSTRAINT institutions_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.permissions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL UNIQUE,
  description text,
  resource character varying NOT NULL,
  action character varying NOT NULL,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT permissions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.program (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  institutions_id uuid,
  degree_id uuid,
  offering_department_id uuid,
  institution_code character varying NOT NULL,
  degree_code character varying NOT NULL,
  offering_department_code character varying,
  program_type character varying,
  program_code character varying NOT NULL,
  program_name character varying NOT NULL,
  display_name character varying,
  description text,
  is_active boolean DEFAULT true,
  sanctioned_strength integer,
  program_duration_yrs integer NOT NULL,
  pattern_type character varying DEFAULT 'Semester'::character varying CHECK (pattern_type::text = ANY (ARRAY['Year'::character varying, 'Semester'::character varying]::text[])),
  assessment_duration character varying,
  part_time boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT program_pkey PRIMARY KEY (id),
  CONSTRAINT program_institutions_id_fkey FOREIGN KEY (institutions_id) REFERENCES public.institutions(id),
  CONSTRAINT program_degree_id_fkey FOREIGN KEY (degree_id) REFERENCES public.degree(id),
  CONSTRAINT program_offering_department_id_fkey FOREIGN KEY (offering_department_id) REFERENCES public.department(id)
);
CREATE TABLE public.regulations (
  id bigint NOT NULL DEFAULT nextval('regulations_id_seq'::regclass),
  regulation_year integer NOT NULL,
  regulation_code character varying NOT NULL UNIQUE,
  status boolean NOT NULL DEFAULT true,
  minimum_internal numeric DEFAULT 0,
  minimum_external numeric DEFAULT 0,
  minimum_attendance numeric NOT NULL,
  minimum_total numeric DEFAULT 0,
  maximum_internal numeric DEFAULT 0,
  maximum_external numeric DEFAULT 0,
  maximum_total numeric DEFAULT 0,
  maximum_qp_marks numeric DEFAULT 0,
  condonation_range_start numeric DEFAULT 0,
  condonation_range_end numeric DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  institutions_id uuid,
  institution_code character varying NOT NULL,
  CONSTRAINT regulations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.role_permissions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  role_id uuid NOT NULL,
  permission_id uuid NOT NULL,
  granted_at timestamp with time zone DEFAULT now(),
  granted_by uuid,
  CONSTRAINT role_permissions_pkey PRIMARY KEY (id),
  CONSTRAINT role_permissions_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.roles(id),
  CONSTRAINT role_permissions_permission_id_fkey FOREIGN KEY (permission_id) REFERENCES public.permissions(id),
  CONSTRAINT role_permissions_granted_by_fkey FOREIGN KEY (granted_by) REFERENCES public.users(id)
);
CREATE TABLE public.roles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL UNIQUE,
  description text,
  is_system_role boolean DEFAULT false,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT roles_pkey PRIMARY KEY (id)
);
CREATE TABLE public.section (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  institutions_id uuid,
  institution_code character varying NOT NULL,
  section_name character varying NOT NULL,
  section_id character varying NOT NULL,
  section_description text,
  arrear_section boolean DEFAULT false,
  status boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT section_pkey PRIMARY KEY (id),
  CONSTRAINT section_institutions_id_fkey FOREIGN KEY (institutions_id) REFERENCES public.institutions(id)
);
CREATE TABLE public.semester (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  institutions_id uuid,
  degree_id uuid,
  institution_code character varying NOT NULL,
  degree_code character varying NOT NULL,
  semester_name character varying NOT NULL,
  display_name character varying,
  student_group character varying,
  display_order integer,
  initial_semester boolean DEFAULT false,
  terminal_semester boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT semester_pkey PRIMARY KEY (id),
  CONSTRAINT semester_institutions_id_fkey FOREIGN KEY (institutions_id) REFERENCES public.institutions(id),
  CONSTRAINT semester_degree_id_fkey FOREIGN KEY (degree_id) REFERENCES public.degree(id)
);
CREATE TABLE public.sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  session_token character varying NOT NULL UNIQUE,
  refresh_token character varying,
  device_info jsonb DEFAULT '{}'::jsonb,
  ip_address inet,
  user_agent text,
  is_active boolean DEFAULT true,
  expires_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sessions_pkey PRIMARY KEY (id),
  CONSTRAINT sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.transaction_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  session_id uuid,
  action character varying NOT NULL,
  resource_type character varying,
  resource_id character varying,
  old_values jsonb,
  new_values jsonb,
  ip_address inet,
  user_agent text,
  status character varying DEFAULT 'success'::character varying,
  error_message text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT transaction_logs_pkey PRIMARY KEY (id),
  CONSTRAINT transaction_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT transaction_logs_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.sessions(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email character varying NOT NULL UNIQUE,
  full_name character varying NOT NULL,
  username character varying UNIQUE,
  avatar_url text,
  bio text,
  website text,
  location text,
  date_of_birth date,
  phone character varying,
  phone_number character varying,
  is_active boolean DEFAULT true,
  is_verified boolean DEFAULT false,
  role character varying DEFAULT 'user'::character varying,
  institution_id character varying,
  is_super_admin boolean DEFAULT false,
  permissions jsonb DEFAULT '{}'::jsonb,
  preferences jsonb DEFAULT '{}'::jsonb,
  metadata jsonb DEFAULT '{}'::jsonb,
  profile_completed boolean DEFAULT false,
  last_login timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT users_pkey PRIMARY KEY (id)
);